### ISSUE TITLE
Getting a crash

### ISSUE THREAD

**Issue by PinkalBaleshwaria** [devsideal/ReadMoreOption#10]
Here is the stack trace of crash

 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
        at com.devs.readmoreoption.ReadMoreOption$1.run(ReadMoreOption.java:90)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by islamYMansour** [comment]
whats sol
