### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by thinhkaku** [devsideal/ReadMoreOption#15]
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.substring(String.java:2064)
        at java.lang.String.subSequence(String.java:2107)
        at com.devs.readmoreoption.ReadMoreOption$1.run(ReadMoreOption.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by dasirahul7** [comment]
Same error message I'm getting, Is there any solution for that?

**Comment by nowjordanhappy** [comment]
I don't know if it's the same error but I fixe for StringIndexOutOfBoundsException. Try this PR https://github.com/devendroid/ReadMoreOption/pull/19
