### ISSUE TITLE
StringIndexOutOfBound Exception

### ISSUE THREAD

**Issue by HaXxanParhar** [devsideal/ReadMoreOption#17]
I'm using the TextViewOptions in RecyclerView. Following is the crash that I'm facing:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.haxxan.xzit, PID: 15726
    java.lang.StringIndexOutOfBoundsException: length=16; index=108
        at java.lang.String.substring(String.java:2060)
        at com.devs.readmoreoption.ReadMoreOption$1.run(ReadMoreOption.java:97)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

**Comment by nowjordanhappy** [comment]
https://github.com/devendroid/ReadMoreOption/pull/19 I hope this fix your error, I found out there is a validation in the java file before migrate to kotlin.

![Captura de Pantalla 2023-01-13 a la(s) 11 55 18](https://user-images.githubusercontent.com/26355419/212375582-0b7428e2-b586-4092-b301-2edd9e9c9b6c.png)
